WARNING:discord.ext.commands.bot:Privileged message content intent is missing, commands may not work as expected.
ERROR:discord.ext.commands.bot:Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "ªüÃZ" is not found
WARNING:discord.ext.commands.bot:Privileged message content intent is missing, commands may not work as expected.
WARNING:discord.ext.commands.bot:Privileged message content intent is missing, commands may not work as expected.
WARNING:discord.ext.commands.bot:Privileged message content intent is missing, commands may not work as expected.
WARNING:discord.ext.commands.bot:Privileged message content intent is missing, commands may not work as expected.
WARNING:discord.ext.commands.bot:Privileged message content intent is missing, commands may not work as expected.
WARNING:discord.ext.commands.bot:Privileged message content intent is missing, commands may not work as expected.
WARNING:discord.ext.commands.bot:Privileged message content intent is missing, commands may not work as expected.
WARNING:discord.ext.commands.bot:Privileged message content intent is missing, commands may not work as expected.
WARNING:discord.ext.commands.bot:Privileged message content intent is missing, commands may not work as expected.
ERROR:discord.client:Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\User\Documents\GitHub\OurBot\main.py", line 93, in on_ready
    await called_once_an_hour_at_55().start()
AttributeError: 'coroutine' object has no attribute 'start'
WARNING:discord.ext.commands.bot:Privileged message content intent is missing, commands may not work as expected.
